# Generated by Django 2.1.15 on 2026-03-11 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('triage', '0001_initial'),
        ('admisiones', '0003_auto_20260123_1105'),
        ('autorizaciones', '0004_auto_20260123_1105'),
    ]

    operations = [
        migrations.AddField(
            model_name='autorizaciones',
            name='ingreso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='adm1476', to='admisiones.Ingresos'),
        ),
        migrations.AddField(
            model_name='autorizaciones',
            name='triage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Triage1476', to='triage.Triage'),
        ),
    ]
